# Generated by Django 5.1.1 on 2024-09-22 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtname', models.CharField(max_length=100)),
                ('stname', models.CharField(max_length=100)),
                ('stcode11', models.CharField(max_length=10)),
                ('dtcode11', models.CharField(max_length=10)),
                ('year_stat', models.CharField(max_length=20)),
                ('objectid', models.IntegerField()),
                ('dist_lgd', models.IntegerField()),
                ('state_lgd', models.IntegerField()),
                ('coordinates', models.JSONField()),
            ],
        ),
    ]
